name: e_commerce
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  internet_connection_checker_plus: ^1.0.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300          
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf          
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf          
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf          
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900    